name: 'Action_OpenWrt_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'AX6'
  
runs:
  using: "composite"
  steps:                   
    - name: Organize files         
      working-directory: ${{ github.workspace }}/runner_root/openwrt
      shell: bash
      run: |      
          echo '当前执行步骤：11-打标'
          tag_name=${{ env.REPO_TAG }}-$([[ "${{ env.COMPILE_CONFIG }}" != 'n' ]] && echo ${{ env.COMPILE_CONFIG}} || $([[ "${{ env.COMPILE_CONFIG_DIFF }}" != 'n' ]] && echo ${{ env.COMPILE_CONFIG_DIFF }} || echo ${{ env.COMPILE_CONFIG_BASE}}))
          [[ "${{ env.IMAGEBUILDER }}" = 'y' ]] && tag_name=ImageBuilder-$tag_name
          [[ "${{ env.FILES_CONFIG }}" != 'public' ]] && tag_name=$tag_name-${{ env.FILES_CONFIG }}
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)
          
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          set +e
          echo '当前执行步骤：12-组织产出文件'          
          cd ./runner_root
          echo "targets产出文件："
          tree  ./openwrt/bin/targets/
          rm -rf ./artifact/
          mkdir -p ./artifact/

          echo '当前执行步骤：12.1-组织配置文件：'
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.manifest") ./artifact/
          cp -vr ./openwrt/.config ./artifact/defconfig-${{ env.TAG_NAME }}.config

          echo '当前执行步骤：12.2-组织bin文件：'
          echo '-sysupgrade文件：'
          rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
          
          
          echo '当前执行步骤：12.3-组织tar文件：'
          if [ "${{ env.IMAGEBUILDER }}" = 'y' ] ; then             
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*imagebuilder*") ./artifact/             
             cd ./artifact/
             rename 's/.tar.xz/-${{ env.TAG_NAME }}.tar.xz/' *
             rename 's/.tar.zst/-${{ env.TAG_NAME }}.tar.zst/' *
          fi

          echo '-产出文件总览：'
          ls -hl 
          set -e
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.REPO_TYPE }}-${{ env.TAG_NAME }}
        path: ./runner_root/artifact/
        
    - name: Addtional bin for release      
      shell: bash
      run: |          
          echo '当前执行步骤：13-添加额外发布文件'    
          if [ "${{ env.IMAGEBUILDER }}" = 'y' ] ; then
             cd ./runner_root
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sdk*") ./artifact/
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*toolchain*") ./artifact/
          fi        
