name: 'Action_LeanWRT_composite'
description: 'Action'
inputs:
  ROUTER_MODEL:  
    description: 'MODEL'
    required: true
    default: 'EA8500'
  COMPILE_CONFIG: 
    description: 'CONFIG'
    required: true
    default: 'EA8500-20240511-VPN'
  IMAGEBUILDER: 
    description: 'IMAGEBUILDER'
    required: false
    default: 'n'
  FILES_CONFIG: 
    description: 
    required: false
    default: 'public'
  OP_REPO: 
    description: 
    required: false
    default: 'thinkcyy/LeanWRT'    
  REPO_BRANCH: 
    description: 
    required: false
    default: 'n' 
  REPO_DEPTH: 
    description: 
    required: false
    default: 'all'
  REPO_COMMIT: 
    description: 
    required: false
    default: 'latest'   
  REPO_TYPE: 
    description: 
    required: false
    default: 'LeanWRT'     
runs:
  using: "composite"
  steps:
    - name: Compile      
      shell: bash
      env:
        ROUTER_MODEL: ${{ inputs.ROUTER_MODEL }}   
        COMPILE_CONFIG: ${{ inputs.COMPILE_CONFIG }} 
        FILES_CONFIG: ${{ inputs.FILES_CONFIG }} 
        REPO_TYPE: ${{ inputs.REPO_TYPE }}
      run:  |          
          echo "当前工作目录"
          pwd          
          echo '当前执行步骤：1-下载${{ inputs.REPO_TYPE }}仓库'
          git clone --depth 1  https://github.com/thinkcyy/OpenWRT-Action OpenWRT-Action           
          git clone $([[ ${{ inputs.REPO_DEPTH }} != 'all' ]] && echo --depth ${{ inputs.REPO_DEPTH }} || echo ) https://github.com/${{ inputs.OP_REPO }} $([[ ${{ inputs.REPO_BRANCH }} != 'n' ]] && echo -b ${{ inputs.REPO_BRANCH }} --single-branch|| echo )  ./OpenWRT-Action/openwrt
          cd ./OpenWRT-Action/openwrt
          $([[ ${{ inputs.REPO_COMMIT }} != 'latest' ]] && echo git checkout ${{ inputs.REPO_COMMIT }} || echo )
          COMMITHASH=$(git rev-parse --short HEAD)          
          cd ../../
          tree -L 3
          
          echo '当前执行步骤：2-处理Package'
          cd ./OpenWRT-Action
          echo "当前工作目录"
          pwd 
          tree -L 3
          chmod +x ./${{ inputs.REPO_TYPE }}/scripts/*.sh
          cp -vr ./${{ inputs.REPO_TYPE }}/config/${{ inputs.COMPILE_CONFIG }}.config ./${{ inputs.REPO_TYPE }}/config/config-${{ inputs.ROUTER_MODEL }}.config
          #cp -vr ./${{ inputs.REPO_TYPE }}/config/${{ inputs.COMPILE_CONFIG }}.config ./openwrt/.config
         
          
          ./${{ inputs.REPO_TYPE }}/scripts/prepare.sh
          
          echo '当前执行步骤：3-添加自定义配置files'
          echo "当前工作目录"
          pwd          
          if [ "${{ inputs.FILES_CONFIG }}" != 'public' ] ; then
             # 忽略错误
             set +e
             echo "files版本为${{ inputs.FILES_CONFIG }}"             
             echo "-正在复制common"
             cp -vr ../openwrt-config/common/files ./openwrt/
             echo "-正在复制common-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/common/${{ inputs.FILES_CONFIG }}/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-common"
             cp -vr ../openwrt-config/${{ inputs.ROUTER_MODEL }}/common/files ./openwrt/
             echo "-正在复制${{ env.ROUTER_MODEL }}-${{ env.FILES_CONFIG }}"
             cp -vr ../openwrt-config/${{ inputs.ROUTER_MODEL }}/${{ inputs.FILES_CONFIG }}/files ./openwrt/
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-up
             chmod +x ./openwrt/files/etc/tinc/tincvpn/tinc-down
             echo '-files文件总览：'
             tree ./openwrt/files
             echo '-修改版本号'
             sed -i "s|='R|='${{ inputs.COMPILE_CONFIG }}-$(date +%Y%m%d)-R|g" ./openwrt/package/lean/default-settings/files/zzz-default-settings 
             cat ./openwrt/package/lean/default-settings/files/zzz-default-settings | grep DISTRIB_REVISION
             echo '-撤销默认开启wifi'
             sed -i '/\/etc\/config\/wireless/d' ./openwrt/package/lean/default-settings/files/zzz-default-settings
             sed -i '/\/lib\/wifi\/mac80211.sh/d' ./openwrt/package/lean/default-settings/files/zzz-default-settings             
             echo '-向后调整tinc服务启动次序'
             #sed -i "20i sed -i \'s|START=42|START=99|g\' \/etc\/init.d\/tinc" ./openwrt/package/lean/default-settings/files/zzz-default-settings
             sed -i 's|START=42|START=99|g' ./openwrt/feeds/packages/net/tinc/files/tinc.init
             echo '-移除frp日志'
             #sed -i "20i sed -i \'s|logger -t FRPC \'Shutting down frp service\'|#logger -t FRPC \'Shutting down frp service\'|g\' \/etc\/init.d\/frp" ./openwrt/package/lean/default-settings/files/zzz-default-settings
             sed -i "20i sed -i \'s|logger -t FRPC|#logger -t FRPC|g\' \/etc\/init.d\/frp" ./openwrt/package/lean/default-settings/files/zzz-default-settings
             echo '-zzz-default-settings文件内容：'
             cat ./openwrt/package/lean/default-settings/files/zzz-default-settings
             # 遇错退出
             set -e
          else
             echo '-当前为public版本，跳过'
          fi                       
          
          echo '当前执行步骤：4-编译'
          cd ./openwrt
          echo '当前执行步骤：4.1-下载'
          make download -j$(nproc)
          echo '当前执行步骤：4.2-编译'
          make -j$(nproc) || make -j1 V=s
          
          echo '当前执行步骤：5-打标'
          if [ "${{ inputs.FILES_CONFIG }}" != 'public' ] ; then
             tag_name=${{ inputs.COMPILE_CONFIG }}-${{ inputs.FILES_CONFIG }}
          else
             tag_name=${{ inputs.COMPILE_CONFIG }}
          fi
          
          tag_name=$tag_name-$(date +%Y%m%d-%H%M)-$COMMITHASH
          
          echo $tag_name
          echo "TAG_NAME=$tag_name" >> $GITHUB_ENV  

    - name: Organize files      
      shell: bash
      run: |                             
          echo '当前执行步骤：6-组织产出文件'          
          cd ./OpenWRT-Action
          echo "targets产出文件："
          tree  ./openwrt/bin/targets/
          rm -rf ./artifact/
          mkdir -p ./artifact/
          
          if [ "${{ inputs.IMAGEBUILDER }}" = 'y' ] ; then
             cp -vr ./openwrt/bin/ ./artifact/ 
          else
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*sysupgrade*") ./artifact/
             cp -vrf $(find ./openwrt/bin/targets/ -type f -name "*.buildinfo") ./artifact/
             cp -vr ./openwrt/.config ./artifact/defconfig-${{ env.TAG_NAME }}.config          
             cd ./artifact/
             rename 's/sysupgrade.bin/sysupgrade-${{ env.TAG_NAME }}.bin/' *
          fi                   
          ls -hl
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: ${{ inputs.REPO_TYPE }}-${{ env.TAG_NAME }}
        path: ./OpenWRT-Action/artifact/
