name: 'Action_OpenWrt_composite'
description: 'Action'
inputs:
  CONFIG_VERIFIED:  
    required: false
    default: 'n'
  CONFIG_TO_ADD:  
    required: false
    default: 'n'
  CONFIG_TO_DEL:  
    required: false
    default: 'n'
runs:
  using: "composite"
  steps:
    - name: PrepareSource      
      shell: bash
      env:
        CONFIG_VERIFIED: ${{ inputs.CONFIG_VERIFIED }}
        CONFIG_TO_ADD: ${{ inputs.CONFIG_TO_ADD }}
        CONFIG_TO_DEL: ${{ inputs.CONFIG_TO_DEL }}
      run:  |
          if [ ! -z ${CONFIG_VERIFIED} ] ; then
            for config in $CONFIG_VERIFIED
            do
              sed -i '$a'"${config}"'' ./t
            done
          fi
          
          if [ ! -z ${CONFIG_TO_ADD} ] ; then
            for config in $CONFIG_TO_ADD
            do
              sed -i '$a'"${config}"'' ./t
            done
          fi

          if [ ! -z ${CONFIG_TO_DEL} ] ; then
            for config in $CONFIG_TO_DEL
            do
              sed -i '$a'"${config}"'' ./t
            done
          fi      
